import type { IconType } from "react-icons"
import {
  SiApachekafka,
  SiCss,
  SiDocker,
  SiExpress,
  SiFigma,
  SiGithub,
  SiGo,
  SiHtml5,
  SiJavascript,
  SiLinux,
  SiMongodb,
  SiMongoose,
  SiNextdotjs,
  SiNodedotjs,
  SiPayloadcms,
  SiPostgresql,
  SiReact,
  SiReacthookform,
  SiRedis,
  SiRust,
  SiSequelize,
  SiTanstack,
  SiTypescript,
  SiZod,
} from "react-icons/si"
import { VscVscode } from "react-icons/vsc";
import { DiPhotoshop } from "react-icons/di";

export const skillIcons: Partial<Record<string, IconType>> = {
  HTML: SiHtml5,
  CSS: SiCss,
  JavaScript: SiJavascript,
  TypeScript: SiTypescript,
  "React JS": SiReact,
  "Next JS": SiNextdotjs,
  "Node JS": SiNodedotjs,
  "Express JS": SiExpress,
  "Payload CMS": SiPayloadcms,
  "React Native": SiReact,
  "TanStack Query": SiTanstack,
  "React Hook Form": SiReacthookform,
  Zod: SiZod,
  MongoDB: SiMongodb,
  PostgreSQL: SiPostgresql,
  Redis: SiRedis,
  Mongoose: SiMongoose,
  Sequelize: SiSequelize,
  Docker: SiDocker,
  "Apache Kafka": SiApachekafka,
  Figma: SiFigma,
  GitHub: SiGithub,
  Linux: SiLinux,
  Go: SiGo,
  Rust: SiRust,
  "VS Code": VscVscode,
  Photoshop: DiPhotoshop,
}
